name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t soufianeit/calculator-app .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: login Docker hub
      run: echo "$password" | docker login -u "$username" --password-stdin
    
    - name: push docker image
      run: docker push soufianeit/calculator-app:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Deploy to server
  #     run: |
  #       ssh user@server 'cd /path/to/app && git pull origin main && docker-compose up -d'
  #     # Remplacez 'ssh user@server' par votre méthode de déploiement réelle, par exemple SSH, ou autre

